version: '3.8'

services:
  ytdata:
    build:
      context: .
    depends_on: 
      - postgres
    ports:
      - '8080:8080'

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: youtube
    ports:
      - '5432:5432'
    volumes:
      - persistenceData:/var/lib/postgresql/data

volumes:
  persistenceData:
